name: ChatBubbles
main: ChatBubbles\Main
version: 1.0.1
api: [1.0.0]
load: POSTWORLD
authors: [Comedyman937]
description: "Show players chat messages above their head!"

permissions:
    chatbubbles.show:
        default: true
        description: "Allows the players Chat Bubble to appear!"
